# Tox (http://tox.testrun.org/)

[tox]
envlist = py310, py311, py312

[testenv]
deps = coverage
    pytest
commands = coverage run -m pytest launchd

[testenv:style]
deps = -rrequirements-style.txt
commands = flake8 {posargs} --count --statistics
    flake8 --version
    check-manifest -v

# Release tooling
[testenv:build]
skip_install = true
allowlist_externals = rm
deps =
    build
commands =
    rm -rf build dist
    python -m build --sdist --wheel

[testenv:release]
skip_install = true
allowlist_externals = rm
deps =
    {[testenv:build]deps}
    twine >= 1.5.0
commands =
    {[testenv:build]commands}
    twine check dist/*
    twine upload --skip-existing dist/*
