---
name: unit tests

on:
  - push
  - pull_request

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:  # https://github.com/actions/runner-images#available-images
        os: [macos-10.15, macos-11, macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Install dependencies
        run: |
          python3 --version
          python3 -m pip install --upgrade pip
          pip3 install tox
      - name: Test with tox
        run: tox -e py,style
